FROM python:3.13-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY pyproject.toml uv.lock ./

RUN rm -rf .venv

RUN pip install uv
RUN uv sync --frozen

COPY . .

CMD ["uv", "run", "python", "tasks/extract_realtime.py"]
